ood_dataset:
  name: imagenet_adversarial_ood
  num_classes: 1000

  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False

  pre_size: 224
  image_size: 224
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  split_names: [nearood, farood]
  # val:
  #   data_dir: ./data/images_largescale/
  #   imglist_pth: ./data/benchmark_imglist/imagenet/val_openimage_o.txt
  nearood:
    datasets: [pgd, fgsm, df]
    pgd:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_pgd_resnet50_imagenet.txt
    fgsm:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_fgsm_resnet50_imagenet.txt
    df:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_df_resnet50_imagenet.txt
  farood:
    datasets: [masked_pgd]
    masked_pgd:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_masked_pgd_resnet50_imagenet.txt